@startuml
class EstudiantesController {
    - <<readonly>> _dbContext : UdiDbContext
    + EstudiantesController(dbContext:UdiDbContext)
    + <<async>> GetAll() : Task<ActionResult<IEnumerator<EstudianteDTO>>>
    + <<async>> Get(id:int) : Task<ActionResult<EstudianteDTO>>
    + <<async>> Create(EstudianteDto:EstudianteDTO) : Task<ActionResult<EstudianteDTO>>
    + <<async>> Delete(id:int) : Task<ActionResult<EstudianteDTO>>
    + <<async>> Update(id:int, EstudianteDto:EstudianteDTO) : Task<IActionResult>
}
class EstudianteExtensions <<static>> {
    + {static} ToModel(EstudianteDto:EstudianteDTO, curso:Curso) : Estudiante
    + {static} Update(EstudianteToUpdate:Estudiante, EstudianteDto:EstudianteDTO, curso:Curso) : void
    + {static} ToDTO(Estudiante:Estudiante) : EstudianteDTO
}
ControllerBase <|-- EstudiantesController
@enduml
